name: illinois
description: Illinois client application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.10.12+1012

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  archive: ^2.0.13
  shared_preferences: ^2.0.3
  flutter_swiper: ^1.1.6
  mime_type: ^0.3.2
  location: ^3.2.4
  uni_links: ^0.4.0
  url_launcher: ^6.0.2
  fluttertoast: ^7.1.8
  # Firebase
  firebase_core: ^0.5.0+1
  firebase_messaging: ^7.0.3
  firebase_crashlytics: ^0.2.4
  firebase_ml_vision: ^0.11.0
  # End Firebase
  logger: ^0.9.4
  flutter_local_notifications: ^4.0.1+1
  sprintf: ^6.0.0
  sqflite: ^2.0.0+2
  encrypt: ^4.1.0
  package_info: ^2.0.0
  device_info: ^2.0.0
  connectivity: ^3.0.2
  collection: ^1.15.0
  uuid: ^2.2.2
  image_picker: ^0.6.7+22
  path_provider: ^2.0.1
  cookie_jar: ^2.0.0
  #flutter_html: ^1.0.2 # Rollback flutter_html to 0.11.1 due to accessibility issue https://github.com/rokwire/safer-illinois-app/issues/195
  flutter_html: ^1.2.0
  qr_flutter: ^3.2.0
  webview_flutter: ^1.0.7
  dotted_border: ^1.0.7
  flutter_image_compress: ^0.7.0
  #barcode_scan: 2.0.2 # Explicitly use older version of the plugin. The latest one does not work!
  barcode_scan: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - images/
  - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProximaNovaBlack
      fonts:
        - asset: fonts/proximanova-black.otf
    - family: ProximaNovaBlackIt
      fonts:
        - asset: fonts/proximanova-blackit.otf
    - family: ProximaNovaBold
      fonts:
        - asset: fonts/proximanova-bold.otf
    - family: ProximaNovaBoldIt
      fonts:
        - asset: fonts/proximanova-boldit.otf
    - family: ProximaNovaExtraBold
      fonts:
        - asset: fonts/proximanova-extrabold.otf
    - family: ProximaNovaExtraBoldIt
      fonts:
        - asset: fonts/proximanova-extraboldit.otf
    - family: ProximaNovaLight
      fonts:
        - asset: fonts/proximanova-light.otf
    - family: ProximaNovaLightIt
      fonts:
        - asset: fonts/proximanova-lightit.otf
    - family: ProximaNovaMedium
      fonts:
        - asset: fonts/proximanova-medium.otf
    - family: ProximaNovaMediumIt
      fonts:
        - asset: fonts/proximanova-mediumit.otf
    - family: ProximaNovaRegular
      fonts:
        - asset: fonts/proximanova-regular.otf
    - family: ProximaNovaRegularIt
      fonts:
        - asset: fonts/proximanova-regularit.otf
    - family: ProximaNovaSemiBold
      fonts:
        - asset: fonts/proximanova-semibold.otf
    - family: ProximaNovaSemiBoldIt
      fonts:
        - asset: fonts/proximanova-semiboldit.otf
    - family: ProximaNovaThin
      fonts:
        - asset: fonts/proximanova-thin.otf
    - family: ProximaNovaThinIt
      fonts:
        - asset: fonts/proximanova-thinit.otf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
